### ISSUE TITLE
raft-rs in github is out of sync with the same version in crates.io

### ISSUE THREAD

**Issue by whfuyn** [tikv/raft-rs#390]
Hi, I was recently using raft-rs in my project. I added `raft-rs = "0.6.0-alpha"` in my `Cargo.toml`, and followed the examples to write my own server. But it turned out some field and methods were missing, like
```rust
        s.mut_metadata().mut_conf_state().voters = vec![1]; // no voters
        store.wl().set_conf_state(cs); // no wl
```
After some painful investigations, I found that the raft-rs in `.Cargo/registry/src/github.com.../raft-0.6.0-alpha` were different from the one I saw in github, which didn't use `voters` in the example, and the proto file weren't the same too.

Maybe it needs an update? It really confuses an inexperience user like me since it has the same version.

**Comment by Fullstop000** [comment]
@whfuyn You can get rid of it by adding things below in your `Cargo.toml`
```toml
[dependencies]
raft = "0.6.0-alpha"

[patch.crates-io]
raft = { git = "https://github.com/tikv/raft-rs", branch = "master", default-features = false }
raft-proto = { git = "https://github.com/tikv/raft-rs", branch = "master", default-features = false }
```
